// Generated by BUCKLESCRIPT VERSION 4.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var WithState$ReactTemplate = require("./WithState.bs.js");
var CounterReducer$ReactTemplate = require("./CounterReducer.bs.js");
var StateRenderProp$ReactTemplate = require("./StateRenderProp.bs.js");
var WithStateRecompose$ReactTemplate = require("./WithStateRecompose.bs.js");

var component = ReasonReact.statelessComponent("App");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, React.createElement("h3", undefined, "Reducer component only"), ReasonReact.element(undefined, undefined, CounterReducer$ReactTemplate.make(/* array */[])), React.createElement("hr", undefined), React.createElement("h3", undefined, "WithState from Recompose"), ReasonReact.element(undefined, undefined, WithStateRecompose$ReactTemplate.make(/* array */[])), React.createElement("hr", undefined), React.createElement("h3", undefined, "WithState ReasonML"), ReasonReact.element(undefined, undefined, WithState$ReactTemplate.make(/* array */[])), React.createElement("hr", undefined), React.createElement("h3", undefined, "RenderProp ReasonML"), ReasonReact.element(undefined, undefined, StateRenderProp$ReactTemplate.Counter[/* make */0](/* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
