// Generated by BUCKLESCRIPT VERSION 4.0.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("CounterReducer");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", undefined, "Count: " + String(self[/* state */1][/* counter */0]), React.createElement("button", {
                              onClick: (function () {
                                  return Curry._1(self[/* send */3], /* IncrementOn */Block.__(0, [2]));
                                })
                            }, "Inc"), React.createElement("button", {
                              onClick: (function () {
                                  return Curry._1(self[/* send */3], /* DecrementOn */Block.__(1, [3]));
                                })
                            }, "Dec"));
            }),
          /* initialState */(function () {
              return /* record */[/* counter */0];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action.tag) {
                return /* Update */Block.__(0, [/* record */[/* counter */state[/* counter */0] - action[0] | 0]]);
              } else {
                return /* Update */Block.__(0, [/* record */[/* counter */state[/* counter */0] + action[0] | 0]]);
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
