// Generated by BUCKLESCRIPT VERSION 4.0.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function StateComponent() {
  var component = ReasonReact.reducerComponent("WithState");
  var make = function (defaultValue, render, _) {
    return /* record */[
            /* debugName */component[/* debugName */0],
            /* reactClassInternal */component[/* reactClassInternal */1],
            /* handedOffState */component[/* handedOffState */2],
            /* willReceiveProps */component[/* willReceiveProps */3],
            /* didMount */component[/* didMount */4],
            /* didUpdate */component[/* didUpdate */5],
            /* willUnmount */component[/* willUnmount */6],
            /* willUpdate */component[/* willUpdate */7],
            /* shouldUpdate */component[/* shouldUpdate */8],
            /* render */(function (self) {
                return Curry._2(render, self[/* state */1], self[/* send */3]);
              }),
            /* initialState */(function () {
                return defaultValue;
              }),
            /* retainedProps */component[/* retainedProps */11],
            /* reducer */(function (action, _) {
                return /* Update */Block.__(0, [action[0]]);
              }),
            /* subscriptions */component[/* subscriptions */13],
            /* jsElementWrapped */component[/* jsElementWrapped */14]
          ];
  };
  return /* module */[
          /* component */component,
          /* make */make
        ];
}

var component = ReasonReact.reducerComponent("WithState");

function make(defaultValue, render, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return Curry._2(render, self[/* state */1], self[/* send */3]);
            }),
          /* initialState */(function () {
              return defaultValue;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              return /* Update */Block.__(0, [action[0]]);
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var CounterState = /* module */[
  /* component */component,
  /* make */make
];

function make$1() {
  return make(0, (function (state, send) {
                return React.createElement("div", undefined, "Count: " + String(state), React.createElement("button", {
                                onClick: (function () {
                                    return Curry._1(send, /* UpdateValue */[state + 2 | 0]);
                                  })
                              }, "Inc"), React.createElement("button", {
                                onClick: (function () {
                                    return Curry._1(send, /* UpdateValue */[state - 3 | 0]);
                                  })
                              }, "Dec"));
              }), /* array */[]);
}

var Counter = /* module */[/* make */make$1];

exports.StateComponent = StateComponent;
exports.CounterState = CounterState;
exports.Counter = Counter;
/* component Not a pure module */
